version: '2'

networks:
  cataas:
    driver: bridge

services:

  cataas-app:
    build:
      context: ./srv
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "${CATAAS_APP_PHP_VERSION}"
    image: cataas-app
    container_name: cataas-app
    volumes:
      - "./src:/var/www"
    command: sh -c "composer install --ignore-platform-reqs && apache2-foreground"
    ports:
      - "8881:8881"
    networks:
      - cataas
    restart: unless-stopped

