version: '2'

networks:
  cataas:
    driver: bridge

services:

  cataas-app:
    build:
      context: ./srv/cataas-app
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "${CATAAS_APP_PHP_VERSION}"
    image: cataas-app
    container_name: cataas-app
    volumes:
      - "./src:/var/www"
    ports:
      - "8881:8881"
    networks:
      - cataas
    restart: unless-stopped

